### ISSUE TITLE
Do you have the description of the CTF problem and the solution method?

### ISSUE THREAD

**Issue by 851579181** [JstnVltt/ctf#1]
Do you have the description of the CTF problem and the solution method?

**Comment by JstnVltt** [comment]
I didn't do any description or write-up when I first did them but that's a good idea. I will work on it.

**Comment by JstnVltt** [comment]
I added Solutions for each CTF in each repertory, as well as an Overview.md to quicly see each CTF goal. I hope it will help understanding the CTFs ! I close this issue.

**Comment by 851579181** [comment]
Thank you. That was a big help
